### PR TITLE
fix #638

### LINKED ISSUE #638: Only show job error is the last action failed
This means is the last action was successful, ignore previously failed jobs for the same action.

### PR DESCRIPTION
**Pull request by mebster**

### CODE REVIEW

File: code/src/cljs/sixsq/nuvla/ui/main/components.cljs [hunk 1]
```diff
@@ -78,23 +78,32 @@
...
-                (not (@errors-dissmissed id))
-                (some? last-failed-job))
-          [ui/Message {:error      true
-                       :on-dismiss #(swap! errors-dissmissed conj id)}
-           [ui/MessageHeader
-            {:style    {:cursor "pointer"}
-             :on-click #(dispatch [set-active-tab-index-event job-tab-index])}
-            (str "Job " action " failed")]
-           [ui/MessageContent last-line]])))))
+      (let [all-jobs             (subscribe [job-subs])
```
Comment (0xbase12) [inline code/src/cljs/sixsq/nuvla/ui/main/components.cljs:84]: What about this equivalent implementation ?

```
(defn ErrorJobsMessage
  [_job-subs _set-active-tab-index-event _job-tab-index]
  (let [tr                (subscribe [::i18n-subs/tr])
        errors-dissmissed (r/atom #{})]
    (fn [job-subs set-active-tab-index-event job-tab-index]
      (let [fn-filter (fn [coll _action jobs]
                                           (let [{:keys [id state] :as last-job} (first jobs)]
                                             (if (and (= state "FAILED") (not (@errors-dissmissed id)))
                                               (conj coll last-job)
                                               coll)))
            failed-jobs                  (->> (subscribe [job-subs])
                                              deref
                                              :resources
                                              (group-by :action)
                                              (reduce-kv fn-filter [])
                                              (sort-by :updated))]
        [:<>
         (doall
           (for [{:keys [id action status-message]} failed-jobs]
             ^{:key id}
             [ui/Message {:error      true
                          :on-dismiss #(swap! errors-dissmissed conj id)}
              [ui/MessageHeader
               {:style    {:cursor "pointer"}
                :on-click #(dispatch [set-active-tab-index-event job-tab-index])}
               (str (str/capitalize (@tr [:job])) " " action " " (@tr [:failed]))]
              [ui/MessageContent (last (str/split-lines (or status-message "")))]]))]))))
```

Comment (0xbase12) [reply code/src/cljs/sixsq/nuvla/ui/main/components.cljs:84]: The sort-by is extra here to keep last updated jobs order when displaying
